import {
  BULK_AI_REVIEW_COMMENTS,
  BULK_CONVENTION_SEEDS,
  BULK_INCIDENT_SEEDS,
  BULK_LEGACY_SYSTEM_NAMES,
  BULK_MIGRATION_BLOCKERS,
  BULK_REFACTOR_SEEDS,
} from "./content-pool-bulk";

export function pick<T>(arr: readonly T[]): T {
  return arr[Math.floor(Math.random() * arr.length)]!;
}

/** 25+ fictional legacy system / service names */
export const LEGACY_SYSTEM_NAMES = [
  "invoice-orchestrator-v2-final",
  "auth-bridge-classic",
  "temporary-billing-adapter",
  "customer-sync-daemon",
  "monolith-observer-service",
  "routing-shim-prod",
  "nightly-reconciliation-daemon",
  "event-bus-probably",
  "permissions-cache-sidecar",
  "reporting-rollup-staging-only",
  "legacy-webhook-receiver",
  "sku-normalizer-temp",
  "fulfillment-bridge-2017",
  "entitlement-mirror-service",
  "audit-trail-writer-v1",
  "coupon-engine-resurrected",
  "inventory-shadow-reader",
  "notification-dispatcher-old",
  "pricing-rules-sandbox-live",
  "partner-feed-ingestor",
  "session-hint-service",
  "document-render-proxy",
  "tax-calc-fallback",
  "warehouse-export-scheduler",
  "identity-lookup-cache",
  "catalog-sync-intermediary",
  "refund-processor-maybe",
  "usage-meter-aggregator",
  "checkout-facade-temp",
  "loyalty-points-ledger-old",
  "shipping-rate-estimator-v1",
  "subscription-renewal-guesswork",
  "vendor-punchout-adapter",
  "gdpr-export-batch-manual",
  "search-index-warmup-job",
  "promo-code-validator-legacy",
  "cart-abandonment-nagger",
  "fraud-score-sidecar-beta",
  "email-template-renderer-v3",
  "mobile-api-compatibility-shim",
  "invoice-pdf-generator-classic",
  "rate-limit-enforcer-maybe",
  "user-preference-mirror",
  "deployment-freeze-override-svc",
  "sla-breach-calculator-draft",
  "onboarding-wizard-backend-2015",
  "feature-toggle-admin-old",
  "cross-region-replicator-temp",
  "support-ticket-enricher",
  "legacy-soap-gateway-wrapper",
  "metrics-cardinality-exploder",
  ...BULK_LEGACY_SYSTEM_NAMES,
] as const;

/** Graph node IDs are stable; labels come from the dependency map seed set */
export const DEPENDENCY_MAP_LABELS: Record<string, { label: string; ver: string }> = {
  "monolith-core": { label: "monolith-observer-service", ver: "v3.14.159 · deprecated" },
  "api-gateway": { label: "routing-shim-prod", ver: "owner: unknown" },
  tmp_service_FINAL: { label: "temporary-billing-adapter", ver: "since 2016" },
  "migration-target": { label: "migration-target", ver: "status: blocked" },
  "cron-v1-backup": { label: "nightly-reconciliation-daemon", ver: "do not remove" },
  "auth-legacy": { label: "auth-bridge-classic", ver: "MD5 · working" },
  data2_final_new: { label: "customer-sync-daemon", ver: "preserved asset" },
  "kafka-maybe": { label: "event-bus-probably", ver: "provisioned never" },
};

export interface ConventionSeed {
  name: string;
  originStory: string;
  currentValue: string;
  currentCost: string;
  status: "Active" | "Disputed" | "Zombie" | "Deprecated but enforced";
}

/** 25+ obsolete conventions — fictional, exaggerated */
export const CONVENTION_SEEDS: ConventionSeed[] = [
  {
    name: "All temporary files must be reviewed quarterly",
    originStory: "Audit finding from a migration that never shipped",
    currentValue: "Calendar filler",
    currentCost: "6h/quarter",
    status: "Deprecated but enforced",
  },
  {
    name: "Every boolean must be named from the previous system's perspective",
    originStory: "Written during a dual-write period in 2014",
    currentValue: "Cognitive tax",
    currentCost: "2 PRs/week",
    status: "Active",
  },
  {
    name: "Deprecated endpoints may not be removed if someone remembers using them",
    originStory: "Customer success escalation, 2019",
    currentValue: "Institutional veto",
    currentCost: "∞ endpoints",
    status: "Active",
  },
  {
    name: "Services created during migration planning are considered permanent",
    originStory: "Architecture review slide became policy",
    currentValue: "Accidental topology",
    currentCost: "+1 service/quarter",
    status: "Active",
  },
  {
    name: "All dashboards must include at least one metric nobody owns",
    originStory: "Executive dashboard template, 2017",
    currentValue: "Alignment theatre",
    currentCost: "1 orphan KPI",
    status: "Zombie",
  },
  {
    name: "Feature flags expire only when production forgets them",
    originStory: "Launch playbook from a product that was sunset",
    currentValue: "Hidden behavior",
    currentCost: "14 active ghosts",
    status: "Zombie",
  },
  {
    name: "Database columns prefixed with tmp_ are load-bearing",
    originStory: "Expedited hotfix during a holiday freeze",
    currentValue: "Schema folklore",
    currentCost: "Migration blocked",
    status: "Deprecated but enforced",
  },
  {
    name: "All errors must map to HTTP 200 with a nested failure code",
    originStory: "Mobile client constraint from a client that left",
    currentValue: "Observability camouflage",
    currentCost: "3am pages",
    status: "Disputed",
  },
  {
    name: "New services require a diagram that will never be updated",
    originStory: "Governance checklist, 2018",
    currentValue: "Documentation debt",
    currentCost: "1 stale PDF",
    status: "Active",
  },
  {
    name: "Cron jobs inherit the schedule of the job they replaced",
    originStory: "Ops handoff note became cron syntax",
    currentValue: "Mystery timing",
    currentCost: "Weekend surprises",
    status: "Zombie",
  },
  {
    name: "Shared libraries may not be upgraded without a steering committee",
    originStory: "Dependency incident that was never root-caused",
    currentValue: "Version stagnation",
    currentCost: "CVE backlog",
    status: "Disputed",
  },
  {
    name: "Environment variables named SECRET are documentation",
    originStory: "Onboarding doc from an intern who became staff",
    currentValue: "Security theatre",
    currentCost: "Audit questions",
    status: "Active",
  },
  {
    name: "Every API must expose a /health that lies politely",
    originStory: "Load balancer requirement, interpreted loosely",
    currentValue: "Green dashboards",
    currentCost: "False confidence",
    status: "Active",
  },
  {
    name: "Code comments that say TODO are considered scheduled work",
    originStory: "Project management integration nobody maintained",
    currentValue: "Backlog inflation",
    currentCost: "400+ TODOs",
    status: "Zombie",
  },
  {
    name: "Staging data must resemble production except when it must not",
    originStory: "Compliance workshop outcome",
    currentValue: "Schrodinger's parity",
    currentCost: "Release roulette",
    status: "Disputed",
  },
  {
    name: "All refactors require a rollback plan for the rollback plan",
    originStory: "Change advisory board template",
    currentValue: "Process nesting",
    currentCost: "2 extra meetings",
    status: "Active",
  },
  {
    name: "Service names ending in -v2 are the current production path",
    originStory: "Naming standard from a replatform that paused",
    currentValue: "Version confusion",
    currentCost: "Onboarding +2 days",
    status: "Deprecated but enforced",
  },
  {
    name: "Manual data fixes are a supported integration pattern",
    originStory: "Runbook titled 'temporary procedure'",
    currentValue: "Human middleware",
    currentCost: "Ops hours",
    status: "Active",
  },
  {
    name: "Logs must not contain customer data unless they already do",
    originStory: "Privacy review with no enforcement budget",
    currentValue: "Policy ambiguity",
    currentCost: "Retention risk",
    status: "Disputed",
  },
  {
    name: "Architecture decisions expire after never",
    originStory: "RFC process that lost its sunset clause",
    currentValue: "Permanent drafts",
    currentCost: "17 open ADRs",
    status: "Zombie",
  },
  {
    name: "Breaking changes require approval from a mailing list nobody reads",
    originStory: "Open-source governance cosplay",
    currentValue: "Silent approval",
    currentCost: "Surprise deploys",
    status: "Zombie",
  },
  {
    name: "All batch jobs must complete before the next batch job starts",
    originStory: "Misread concurrency requirement",
    currentValue: "Serial universe",
    currentCost: "6h nightly window",
    status: "Active",
  },
  {
    name: "Configuration files are immutable after first deploy",
    originStory: "Change freeze that became culture",
    currentValue: "Config archaeology",
    currentCost: "Fear of editing",
    status: "Deprecated but enforced",
  },
  {
    name: "Every microservice must justify itself in a quarterly slide",
    originStory: "FinOps initiative that counted services instead of cost",
    currentValue: "Slide maintenance",
    currentCost: "1 deck/service",
    status: "Active",
  },
  {
    name: "Incident retrospectives must preserve the original workaround",
    originStory: "Postmortem action item: document the hack",
    currentValue: "Institutionalized hacks",
    currentCost: "Permanent workarounds",
    status: "Active",
  },
  {
    name: "Null is a valid business state and also a personality type",
    originStory: "Domain modeling offsite, 2015",
    currentValue: "Semantic drift",
    currentCost: "Nullable everything",
    status: "Disputed",
  },
  {
    name: "Pull requests must reference a ticket that references a slide",
    originStory: "PMO integration from 2016 planning overhaul",
    currentValue: "Triple linkage",
    currentCost: "15 min/PR",
    status: "Active",
  },
  {
    name: "All dates stored as strings in local timezone of whoever wrote it",
    originStory: "Early internationalization attempt",
    currentValue: "Temporal chaos",
    currentCost: "DST incidents",
    status: "Deprecated but enforced",
  },
  {
    name: "Retry logic must retry until someone notices",
    originStory: "Outage where giving up was worse",
    currentValue: "Infinite optimism",
    currentCost: "Thundering herd Fridays",
    status: "Zombie",
  },
  {
    name: "No deploys on days ending in y",
    originStory: "Joke policy that became HR-approved",
    currentValue: "Calendar veto",
    currentCost: "Perpetual Tuesday deploys",
    status: "Disputed",
  },
  {
    name: "Every table needs an is_deleted column that means maybe",
    originStory: "Soft delete pilot that hardened",
    currentValue: "Semantic softening",
    currentCost: "Query confusion",
    status: "Active",
  },
  {
    name: "Vendor SDK versions are pinned to the vendor's mood",
    originStory: "Upgrade broke prod once in 2018",
    currentValue: "Risk aversion",
    currentCost: "CVE acceptance",
    status: "Zombie",
  },
  {
    name: "Engineers must ask permission to delete dead code",
    originStory: "Incident where deleted code was load-bearing",
    currentValue: "Deletion fear",
    currentCost: "Zombie modules",
    status: "Active",
  },
  {
    name: "All incidents require a postmortem before the incident ends",
    originStory: "Process improvement sprint",
    currentValue: "Meta-incidents",
    currentCost: "2x incident duration",
    status: "Disputed",
  },
  {
    name: "Service ownership is implied by git blame",
    originStory: "Cost-saving alternative to a service catalog",
    currentValue: "Blame routing",
    currentCost: "Wrong pings",
    status: "Zombie",
  },
  {
    name: "Configuration must be duplicated across three repos minimum",
    originStory: "Multi-region copy-paste standard",
    currentValue: "Drift guarantee",
    currentCost: "3-way merges",
    status: "Deprecated but enforced",
  },
  {
    name: "Alerts fire only after three customers complain",
    originStory: "Noise reduction initiative",
    currentValue: "Human SLO",
    currentCost: "Late detection",
    status: "Active",
  },
  {
    name: "Documentation is generated from code that is not committed",
    originStory: "Docs-as-code workshop artifact",
    currentValue: "Phantom docs",
    currentCost: "Wiki distrust",
    status: "Zombie",
  },
  {
    name: "API versioning is social, not technical",
    originStory: "Backward compatibility handshake ritual",
    currentValue: "Gentleman's agreement",
    currentCost: "Surprise breaks",
    status: "Disputed",
  },
  {
    name: "All caches must be cleared manually during deploy",
    originStory: "Forgotten cache invalidation incident",
    currentValue: "Ritual deploy step",
    currentCost: "3am runbook",
    status: "Active",
  },
  {
    name: "Monorepo boundaries are enforced by hallway agreements",
    originStory: "Split attempt that ended in truce",
    currentValue: "Organic coupling",
    currentCost: "Import creep",
    status: "Zombie",
  },
  ...BULK_CONVENTION_SEEDS,
];

export interface RefactorSeed {
  title: string;
  owner: string;
  risk: string;
  targetQuarter: string;
  status: "Proposed" | "Discussed" | "Deferred" | "Blocked" | "Forgotten";
  reason: string;
}

/** 25+ refactor queue items */
export const REFACTOR_SEEDS: RefactorSeed[] = [
  { title: "Remove unused billing adapter from 2018", owner: "unknown", risk: "High", targetQuarter: "Q4 FY2026", status: "Deferred", reason: "Still receives traffic on leap days" },
  { title: "Rename temporary customer sync service", owner: "platform", risk: "Medium", targetQuarter: "Q3 FY2026", status: "Discussed", reason: "Name is referenced in three executive dashboards" },
  { title: "Split monolith once stakeholders align", owner: "architecture", risk: "Critical", targetQuarter: "Q4 FY2027", status: "Proposed", reason: "Alignment scheduled quarterly since 2021" },
  { title: "Replace legacy auth bridge after next planning cycle", owner: "security", risk: "Critical", targetQuarter: "Q2 FY2026", status: "Blocked", reason: "Bridge authenticates the billing adapter" },
  { title: "Delete cron job that may still be important", owner: "ops", risk: "Low", targetQuarter: "Q1 FY2026", status: "Forgotten", reason: "Last run succeeded; purpose unknown" },
  { title: "Consolidate duplicate notification dispatchers", owner: "messaging", risk: "High", targetQuarter: "Q4 FY2026", status: "Deferred", reason: "Each dispatcher has a different on-call" },
  { title: "Remove shadow inventory reader", owner: "fulfillment", risk: "Medium", targetQuarter: "Q3 FY2026", status: "Proposed", reason: "Finance still exports from it monthly" },
  { title: "Migrate coupon engine off resurrected codebase", owner: "unknown", risk: "High", targetQuarter: "Q4 FY2026", status: "Blocked", reason: "Black Friday depends on undocumented branch" },
  { title: "Collapse permissions cache sidecar into main API", owner: "platform", risk: "Medium", targetQuarter: "Q2 FY2026", status: "Discussed", reason: "Sidecar is faster than the API it protects" },
  { title: "Retire reporting rollup that only runs in staging", owner: "data", risk: "Low", targetQuarter: "Q1 FY2027", status: "Forgotten", reason: "Staging report became board metric by accident" },
  { title: "Replace webhook receiver with managed gateway", owner: "integrations", risk: "Medium", targetQuarter: "Q3 FY2026", status: "Deferred", reason: "47 partners hardcoded the old URL" },
  { title: "Unify tax calc fallback with primary engine", owner: "finance", risk: "Critical", targetQuarter: "Q4 FY2026", status: "Blocked", reason: "Fallback handles three states correctly; primary handles forty" },
  { title: "Delete entitlement mirror after cutover", owner: "unknown", risk: "High", targetQuarter: "Q2 FY2027", status: "Proposed", reason: "Cutover deferred to next planning cycle" },
  { title: "Remove partner feed ingestor duplicate", owner: "integrations", risk: "Medium", targetQuarter: "Q4 FY2026", status: "Discussed", reason: "Duplicates disagree safely most Tuesdays" },
  { title: "Simplify session hint service responsibilities", owner: "identity", risk: "Low", targetQuarter: "Q1 FY2026", status: "Forgotten", reason: "Hint service now owns login" },
  { title: "Merge warehouse export schedulers", owner: "data", risk: "Medium", targetQuarter: "Q3 FY2026", status: "Deferred", reason: "Each scheduler emails a different VP" },
  { title: "Replace document render proxy with CDN rule", owner: "platform", risk: "Low", targetQuarter: "Q2 FY2026", status: "Proposed", reason: "Proxy adds latency but feels safer" },
  { title: "Delete usage meter aggregator v1", owner: "billing", risk: "High", targetQuarter: "Q4 FY2026", status: "Blocked", reason: "v2 aggregates differently; finance approved both" },
  { title: "Remove catalog sync intermediary", owner: "commerce", risk: "Medium", targetQuarter: "Q3 FY2027", status: "Deferred", reason: "Intermediary renamed thrice; grep is unreliable" },
  { title: "Refactor refund processor maybe into definite service", owner: "payments", risk: "Critical", targetQuarter: "Q4 FY2026", status: "Blocked", reason: "Processor name reflects accurate confidence level" },
  { title: "Deduplicate SKU normalizer pipelines", owner: "catalog", risk: "Medium", targetQuarter: "Q2 FY2026", status: "Discussed", reason: "Pipelines disagree on what a SKU is" },
  { title: "Archive audit trail writer v1", owner: "compliance", risk: "High", targetQuarter: "Q1 FY2027", status: "Deferred", reason: "Auditors prefer the old format" },
  { title: "Remove identity lookup cache warming job", owner: "unknown", risk: "Low", targetQuarter: "Q3 FY2026", status: "Forgotten", reason: "Cache warms itself incorrectly but quickly" },
  { title: "Replace fulfillment bridge from 2017", owner: "logistics", risk: "High", targetQuarter: "Q4 FY2027", status: "Proposed", reason: "Bridge still handles returns for a product line that ended" },
  { title: "Collapse event bus probably into actual bus", owner: "platform", risk: "Medium", targetQuarter: "Q4 FY2026", status: "Blocked", reason: "Bus existence remains unverified" },
  { title: "Delete pricing rules sandbox that runs in prod", owner: "revenue", risk: "Critical", targetQuarter: "Q2 FY2026", status: "Deferred", reason: "Sandbox name was aspirational" },
  { title: "Remove loyalty points ledger double-write", owner: "growth", risk: "High", targetQuarter: "Q3 FY2026", status: "Blocked", reason: "Marketing campaign still references ledger v1" },
  { title: "Replace SOAP gateway wrapper with anything else", owner: "integrations", risk: "Critical", targetQuarter: "Q4 FY2027", status: "Proposed", reason: "One partner still sends XML by fax metaphor" },
  { title: "Delete cart abandonment nagger cron", owner: "growth", risk: "Low", targetQuarter: "Q1 FY2026", status: "Forgotten", reason: "Nags abandoned carts that no longer exist" },
  { title: "Unify fraud score sidecars", owner: "risk", risk: "High", targetQuarter: "Q4 FY2026", status: "Discussed", reason: "Sidecars disagree; fraud still happens" },
  { title: "Retire mobile API compatibility shim", owner: "mobile", risk: "Medium", targetQuarter: "Q2 FY2027", status: "Deferred", reason: "App store version from 2019 still in top 10%" },
  { title: "Remove deployment freeze override service", owner: "platform", risk: "Critical", targetQuarter: "Q4 FY2026", status: "Blocked", reason: "Only way to deploy during freeze is through override" },
  { title: "Collapse email template renderer versions", owner: "comms", risk: "Medium", targetQuarter: "Q3 FY2026", status: "Proposed", reason: "v3 renders; v1 sends" },
  { title: "Delete cross-region replicator temp", owner: "infra", risk: "High", targetQuarter: "Q1 FY2027", status: "Deferred", reason: "Temp has been primary in region B since 2020" },
  { title: "Replace manual GDPR export batch", owner: "legal", risk: "High", targetQuarter: "Q4 FY2026", status: "Blocked", reason: "Batch run by intern script blessed by counsel" },
  { title: "Remove metrics cardinality exploder", owner: "observability", risk: "Medium", targetQuarter: "Q2 FY2026", status: "Discussed", reason: "Exploder is how we know things are alive" },
  { title: "Simplify vendor punchout adapter chain", owner: "procurement", risk: "Low", targetQuarter: "Q3 FY2027", status: "Forgotten", reason: "Chain documented on whiteboard photo" },
  { title: "Migrate subscription renewal guesswork to science", owner: "billing", risk: "Critical", targetQuarter: "Q4 FY2027", status: "Proposed", reason: "Guesswork revenue within 3% of actual" },
  { title: "Delete support ticket enricher duplicate", owner: "support", risk: "Low", targetQuarter: "Q1 FY2026", status: "Deferred", reason: "Enrichers enrich each other recursively" },
  { title: "Remove onboarding wizard backend from 2015", owner: "product", risk: "Medium", targetQuarter: "Q4 FY2026", status: "Blocked", reason: "Wizard still completes for 12% of signups" },
  { title: "Retire feature toggle admin from before toggles", owner: "platform", risk: "High", targetQuarter: "Q2 FY2026", status: "Discussed", reason: "Admin UI toggles toggles that toggle admin" },
  ...BULK_REFACTOR_SEEDS,
];

/** 25+ migration / refactor blockers */
export const MIGRATION_BLOCKERS = [
  "Original owner left with undocumented context",
  "Dashboard depends on field nobody admits to owning",
  "Refactor requires approval from a deprecated team",
  "Staging works because production is different",
  "Migration risk classified as unknowable",
  "Rollback plan requires restoring a database nobody has seen",
  "Compliance badge expires when migration completes",
  "Two services share a secret that is also a hostname",
  "Cutover window conflicts with annual planning freeze",
  "Vendor contract references the old system by pet name",
  "Test environment lacks the bug that makes prod work",
  "Data backfill depends on a script that runs on one laptop",
  "Executive metric uses column added as a hotfix",
  "Feature flag removal would reveal feature flag removal",
  "On-call runbook references engineer who became a gardener",
  "Parallel migration path already marked complete in slide deck",
  "Security scan passes only when legacy auth is enabled",
  "Performance benchmark uses cache warmed by manual SQL",
  "Legal hold on logs that may or may not exist",
  "Integration partner refuses to change URL until Q4",
  "Database migration tool requires version that cannot install",
  "Shadow traffic route has no owner but has budget",
  "Monolith module shares memory with feelings",
  "Service mesh diagram does not match service mesh reality",
  "Success criteria defined as 'no headlines'",
  "Production config diff is three thousand lines of comments",
  "Migration blocked by migration readiness checklist item 1",
  "New system requires data we stopped collecting in 2019",
  "Runbook step 7 references a server decommissioned in 2021",
  "Stakeholder signed off on slides, not on scope",
  "Database foreign key points to table that exists only in staging",
  "Canary deployment canaried the wrong service successfully",
  "Budget approved for discovery phase of discovery phase",
  "Legacy API rate limit is also the integration's heartbeat",
  "Terraform state and reality diverged amicably",
  "Single tenant still on bespoke branch from acquisition",
  "Observability dashboard shows green; customers show otherwise",
  "Migration coach left; playbook is a PDF with no text layer",
  "Hotfix branch became long-term support by accident",
  "Required training module for new system expired in 2018",
  "Data classification unknown; defaulting to permanent retention",
  ...BULK_MIGRATION_BLOCKERS,
] as const;

/** 25+ AI review comments */
export const AI_REVIEW_COMMENTS = [
  "Consider extracting this into a reusable abstraction.",
  "This may be a race condition, depending on context not shown in the diff.",
  "Could this be more generic?",
  "Potential issue: naming may not align with historical intent.",
  "Have you considered adding tests for the behavior you did not change?",
  "This change appears to increase coupling; consider a facade.",
  "Nit: variable name could be more enterprise.",
  "Is there a reason this logic is not in the legacy bridge?",
  "Suggest documenting why this workaround remains necessary.",
  "This might benefit from an additional indirection layer.",
  "Unclear if this respects the quarterly naming freeze.",
  "Consider splitting this PR into seventeen smaller PRs.",
  "Possible null pointer in a code path the diff does not touch.",
  "Have you verified this against the staging-only reporting path?",
  "This pattern resembles a deprecated approach; intentional?",
  "Could we add a feature flag for the feature flag?",
  "Performance: have you benchmarked on the laptop from 2018?",
  "Security: ensure secrets are not committed unless historically required.",
  "Readability: consider renaming to match the previous system's dialect.",
  "This might break the manual fix script run every Monday.",
  "Suggest adding a comment explaining why the comment was removed.",
  "Is this consistent with the architecture diagram from 2017?",
  "Potential duplication with a service whose name we cannot locate.",
  "Consider deferring this change until after the planning cycle.",
  "This could be simplified by adding another service.",
  "Have you considered whether this needs a rollback plan for the rollback?",
  "Style: appears functional; consider more abstraction anyway.",
  "This function could be replaced by a well-timed pause.",
  "Have you considered whether this change respects the sacred cow?",
  "Nit: indentation suggests moral ambiguity.",
  "This might be simpler if we added a committee.",
  "Unclear if this aligns with the diagram in the all-hands deck.",
  "Suggest extracting this into a service that extracts services.",
  "Potential performance issue on hardware we no longer own.",
  "Is this idempotent? Is anything here idempotent?",
  "Consider adding telemetry for the telemetry pipeline.",
  "This rename may break the grep-based integration.",
  "Have you updated the wiki page nobody reads?",
  "Could we gate this behind the gate that gates gates?",
  "This looks like it might cause an incident; consider a pre-mortem.",
  "Style: brave choice to ship code in a migration freeze.",
  "Does this need a feature flag or a prayer?",
  "Consider inlining this; or extract; or both; sequentially.",
  "This constant should probably be an environment variable or a rumor.",
  "Have you verified behavior when the cache lies?",
  "Suggest deferring until after the deferral committee meets.",
  ...BULK_AI_REVIEW_COMMENTS,
] as const;

export interface IncidentSeed {
  level: "ok" | "info" | "warn" | "blocked" | "critical" | "noise";
  text: string;
}

/** 25+ incident log messages */
export const INCIDENT_SEEDS: IncidentSeed[] = [
  { level: "warn", text: "migration deferred to Q4 FY2026" },
  { level: "info", text: "ownership clarification failed successfully" },
  { level: "critical", text: "developer attempted simplification" },
  { level: "noise", text: "18 low-context review comments generated" },
  { level: "ok", text: "obsolete convention preserved" },
  { level: "blocked", text: "refactor pipeline rescheduled — stakeholder alignment pending" },
  { level: "warn", text: "accidental coupling detected between unrelated services" },
  { level: "info", text: "auto-layout applied: readability decreased 47%" },
  { level: "ok", text: "health check returned 200 while internally screaming" },
  { level: "critical", text: "production hotfix promoted to architectural pattern" },
  { level: "noise", text: "AI reviewer suggested more abstraction in config file" },
  { level: "warn", text: "temporary service entered year nine of operation" },
  { level: "info", text: "convention dispute escalated to calendar invite" },
  { level: "blocked", text: "migration target snapped back to origin" },
  { level: "ok", text: "dashboard metric refreshed with estimated estimates" },
  { level: "warn", text: "cron job ran successfully for unknown reasons" },
  { level: "info", text: "new intermediary service added to reduce complexity" },
  { level: "critical", text: "developer removed comment marked DO NOT REMOVE" },
  { level: "noise", text: "batch review classified 0 comments as useful" },
  { level: "blocked", text: "cutover postponed pending cutover readiness review" },
  { level: "ok", text: "compliance badge renewed without reading requirements" },
  { level: "warn", text: "dependency graph layout randomized for fairness" },
  { level: "info", text: "refactor forgotten per standard procedure" },
  { level: "critical", text: "staging parity achieved by breaking production differently" },
  { level: "noise", text: "14 AI review comments generated" },
  { level: "ok", text: "control plane initialized — migration blocked by default" },
  { level: "warn", text: "migration_path: loop detected → origin" },
  { level: "critical", text: "developer attempted to move migration-target" },
  { level: "critical", text: "migration run attempted — pipeline blocked" },
  { level: "info", text: "node added to graph; topology now theoretically connected" },
  { level: "warn", text: "simplify architecture produced additional facade layer" },
  { level: "blocked", text: "refactor marked forgotten; memory also forgotten" },
  { level: "noise", text: "review bot asked for tests on comment-only change" },
  { level: "ok", text: "convention marked zombie; still enforced at build time" },
  { level: "warn", text: "dependency map scrolled; ownership unchanged" },
  { level: "info", text: "blocker generated procedurally; root cause optional" },
  { level: "critical", text: "manual prod fix merged without irony tag" },
  { level: "blocked", text: "cutover checklist item added instead of completed" },
  { level: "noise", text: "AI suggested renaming variable to more enterprise name" },
  { level: "ok", text: "quarterly planning reaffirmed Q4 as strategic horizon" },
  { level: "warn", text: "temporary adapter celebrated ninth birthday" },
  { level: "info", text: "ownership assigned to team alias with no members" },
  { level: "critical", text: "developer read runbook; runbook disclaimed liability" },
  { level: "blocked", text: "migration target elastic-snapped; hope elastic-snapped too" },
  { level: "noise", text: "7 review comments classified as historically motivated" },
  { level: "ok", text: "debt stability increased via deferral, not remediation" },
  ...BULK_INCIDENT_SEEDS,
];

/** 15 fake compliance badges */
export const COMPLIANCE_BADGES = [
  { id: "SOC2-T2T", label: "SOC 2 Type II Theatre", status: "valid" },
  { id: "ISO-NEVER", label: "ISO 27001 Aspirational", status: "pending" },
  { id: "GDPR-ISH", label: "GDPR-ish Readiness", status: "valid" },
  { id: "HIPAA-VIBES", label: "HIPAA Vibes Certified", status: "expired" },
  { id: "PCI-DEFER", label: "PCI Deferred Attestation", status: "valid" },
  { id: "COPPA-MAYBE", label: "COPPA Maybe Compliant", status: "pending" },
  { id: "FedRAMP-SLIDE", label: "FedRAMP Slide Approved", status: "valid" },
  { id: "WCAG-LETTER", label: "WCAG Letter of Intent", status: "valid" },
  { id: "NIST-DRAFT", label: "NIST Draft Forever", status: "pending" },
  { id: "CCPA-EXPORT", label: "CCPA Export Button Exists", status: "valid" },
  { id: "BIPA-UNREAD", label: "BIPA Policy Unread", status: "expired" },
  { id: "CSA-STAR-POSTER", label: "CSA STAR Poster", status: "valid" },
  { id: "ITAR-ACCIDENTAL", label: "ITAR Accidental Coverage", status: "pending" },
  { id: "ADA-TICKET", label: "ADA Backlog Ticket Open", status: "valid" },
  { id: "EU-AI-ACT-FAQ", label: "EU AI Act FAQ Published", status: "valid" },
  { id: "PIPEDA-PDF", label: "PIPEDA PDF Uploaded Once", status: "pending" },
  { id: "LGPD-LATER", label: "LGPD Compliance Later", status: "pending" },
  { id: "SOX-ISH", label: "SOX Controls Self-Certified", status: "valid" },
  { id: "HITECH-MAYBE", label: "HITECH Maybe Later", status: "expired" },
  { id: "FERPA-GUESS", label: "FERPA Best Effort", status: "valid" },
  { id: "AML-TICKET", label: "AML Review Ticket Open", status: "pending" },
  { id: "DORA-DECK", label: "DORA Readiness Deck", status: "valid" },
  { id: "NIS2-NOTED", label: "NIS2 Noted in Meeting", status: "pending" },
  { id: "PCI-SAQ-D", label: "PCI SAQ-D Aspirational", status: "expired" },
  { id: "ISO-42001-SOON", label: "ISO 42001 AI Soon™", status: "pending" },
  { id: "PRIVACY-SHIELD", label: "Privacy Shield Poster (framed)", status: "expired" },
] as const;

/** 15 fake dashboard metrics for marketing telemetry */
export const DASHBOARD_METRICS = [
  { key: "review_noise", value: "+47%", note: "low-context review comments", tone: "text-amber" },
  { key: "deferral_rate", value: "94%", note: "refactors rescheduled to Q4", tone: "text-terminal" },
  { key: "owner_clarity", value: "0", note: "clarified ownership boundaries", tone: "text-dim" },
  { key: "conventions", value: "160+", note: "obsolete conventions preserved", tone: "text-terminal" },
  { key: "blocker_velocity", value: "+3/wk", note: "new migration blockers generated", tone: "text-danger" },
  { key: "bridge_count", value: "11", note: "active architectural bridges", tone: "text-amber" },
  { key: "temp_permanence", value: "8.2yr", note: "avg age of temporary services", tone: "text-deprecated" },
  { key: "alignment", value: "98%", note: "stakeholder alignment theatre", tone: "text-amber" },
  { key: "onboard_dur", value: "3.8x", note: "slower onboarding vs baseline", tone: "text-danger" },
  { key: "graph_coupling", value: "rising", note: "accidental service coupling index", tone: "text-danger" },
  { key: "flag_debt", value: "214", note: "feature flags past sunset date", tone: "text-amber" },
  { key: "runbook_fresh", value: "2016", note: "newest runbook publication year", tone: "text-dim" },
  { key: "migration_risk", value: "theoretical", note: "official migration risk classification", tone: "text-terminal" },
  { key: "facade_depth", value: "4", note: "layers of facades around billing", tone: "text-amber" },
  { key: "incident_noise", value: "62%", note: "incidents classified as noise", tone: "text-muted" },
  { key: "pager_duty", value: "47", note: "open pages with no runbook step", tone: "text-danger" },
  { key: "adr_half_life", value: "∞", note: "avg ADR time in draft state", tone: "text-dim" },
  { key: "facade_growth", value: "+2/qtr", note: "new facades per simplification attempt", tone: "text-amber" },
  { key: "grep_integrations", value: "23", note: "production integrations via grep", tone: "text-deprecated" },
  { key: "q4_capacity", value: "112%", note: "Q4 migration capacity utilization", tone: "text-danger" },
  { key: "todo_half_life", value: "4.7yr", note: "avg age of TODO comments", tone: "text-dim" },
  { key: "shadow_traffic", value: "8%", note: "traffic to services without owners", tone: "text-amber" },
  { key: "rollback_drills", value: "0", note: "successful rollback drills this year", tone: "text-danger" },
  { key: "wiki_accuracy", value: "unverified", note: "internal wiki factual confidence", tone: "text-muted" },
  { key: "bus_factor", value: "1.2", note: "avg engineers who understand billing", tone: "text-danger" },
  { key: "freeze_days", value: "218", note: "days in deploy freeze this fiscal year", tone: "text-terminal" },
] as const;

export const DEFER_MIGRATION_INCIDENTS = [
  "migration deferred to Q4 FY2026",
  "migration deferred pending migration readiness review",
  "cutover rescheduled to align with planning cycle",
  "migration target moved on calendar, not in architecture",
  "Q4 deferral slot filled; next slot: Q4",
  "migration postponed until dependencies achieve sentience",
  "cutover moved to align with fiscal year that never ends",
  "readiness review concluded: not ready, schedule anyway",
  "migration deferred; calendar invite sent to Q4",
] as const;

export const OWNERSHIP_INCIDENTS = {
  failed: [
    "ownership clarification failed successfully",
    "owner identified as distribution list that bounced",
    "ownership matrix updated; all cells now say TBD",
    "clarification meeting scheduled; no attendees confirmed",
    "owner field set to former intern's LinkedIn URL",
    "RACI matrix updated; all roles say Consulted",
    "service catalog entry points to 404; ownership confirmed",
  ],
  brief: [
    "ownership briefly clarified, then reverted",
    "temporary owner assigned: team@company.invalid",
    "wiki page updated; immediately contradicted by production",
    "on-call rotation updated; phone tree still wrong",
    "ownership doc signed; signatory no longer employed",
  ],
} as const;

export const SIMPLIFY_VER_LABELS = [
  "narrows nothing",
  "added for clarity",
  "interim forever",
  "reduces coupling by adding coupling",
  "approved in slide deck",
  "narrows scope by widening scope",
  "temporary until proven load-bearing",
  "replaces 1 service with 2 services",
  "strangler fig node",
  "documented as interim since 2014",
] as const;
