version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "q4"
    commit-message:
      prefix: "deps(actions)"

  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "q4"
    commit-message:
      prefix: "deps(bun)"
