version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "q4"
    commit-message:
      prefix: "chore(actions)"
    assignees:
      - gabroberge

  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "q4"
    commit-message:
      prefix: "chore(bun)"
    assignees:
      - gabroberge
